version: "3.8"

services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu:latest
    restart: on-failure
    command: ["sleep","infinity"]
    volumes:
      - ./data:/mnt/data
    environment:
      SYS_NAME: ubuntu-container

volumes: 
  data:
  
